version: '3.8'

services:
  app:
    build: .
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - 8000:8000
    environment:
      - DATABASE=mongodb://mongo:27017/emaildb
      - RABBIT_URL=amqp://rabbitmq:5672
    networks:
      - rabbitmq_nodejs

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh mongo:27017/emaildb --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - rabbitmq_nodejs

  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_nodejs
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  rabbitmq_nodejs:
