# Use a node.js base image
FROM node:18-alpine as base

# Create and set the working directory
WORKDIR /app

# Copy package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port the application listens on
EXPOSE 8000

# Set environment variables
ENV NODE_ENV=production
ENV MONGO_URL=mongodb://mongo:27017/emaildb
ENV RABBITMQ_URL=amqp://rabbitmq:5672

# Build the application
RUN npm run build

# Start the application
CMD ["npm", "start"]
