# Use a Node.js base image
FROM node:18-alpine as base

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application code to the container
COPY . .

# Expose port 8000 for the application
EXPOSE 8000

# Set environment variables
# ENV DATABASE mongodb://mongo:27017/emaildb
# ENV RABBIT_URL amqp://rabbitmq:5672

# Start the application
CMD ["npm", "run", "start"]