version: '3.8'

services:
  app:
    container_name: app
    build: .
    depends_on:
      - rabbitmq
      - mongo
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      - DATABASE=mongodb://mongo:27017/emaildb
      - RABBIT_URL=amqp://rabbitmq:5672
    networks:
      - rabbitmq_nodejs

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    logging:
      driver: none
    volumes:
      - ./mongo/data:/data/db
    networks:
      - rabbitmq_nodejs

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    logging:
      driver: none
    networks:
      - rabbitmq_nodejs

networks:
  rabbitmq_nodejs:
    driver: bridge